"""Add instagram_url to profile

Revision ID: b9686973730f
Revises: c115ecb2c5ca
Create Date: 2026-08-10 17:58:22.473358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9686973730f'
down_revision: Union[str, Sequence[str], None] = 'c115ecb2c5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('instagram_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'instagram_url')
    # ### end Alembic commands ###
