"""add cv_url to profile

Revision ID: c115ecb2c5ca
Revises: f5b91635738f
Create Date: 2026-08-09 15:33:07.798833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c115ecb2c5ca'
down_revision: Union[str, Sequence[str], None] = 'f5b91635738f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('cv_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'cv_url')
    # ### end Alembic commands ###
